In [11]:
import numpy as np
import pandas as pd

# Sample Dataset

In [80]:
sensus = {
    "tinggi": [158,170,183,191,155,163,180,158,178],
    "berat": [64,86,84,80,49,59,67,54,67],
    "jk": [
        "pria","pria","pria","pria","wanita","wanita","wanita","wanita","wanita"
    ]
}

sensus_df = pd.DataFrame(sensus)

In [81]:
sensus_df

tinggi  berat      jk
0     158     64    pria
1     170     86    pria
2     183     84    pria
3     191     80    pria
4     155     49  wanita
5     163     59  wanita
6     180     67  wanita
7     158     54  wanita
8     178     67  wanita

# Membuat Features and Target Datasets

In [82]:
# split datasets into features and target
X_train = np.array(sensus_df[["tinggi", "jk"]])
y_train = np.array(sensus_df[["berat"]])

# Convert dimension of target into 1 dimension
y_train1D = y_train.flatten()

print(X_train.shape)
print(y_train.shape)
print(y_train1D.shape)

(9, 2)
(9, 1)
(9,)


# Merubah isi dari Jenis Kelamin menjadi angka

In [83]:
from sklearn.preprocessing import LabelBinarizer

print("dataset X_train:")
print(X_train)
print()

# Transpose X_train supaya bisa dibagi kebeberapa bagian
X_train_transpose = np.transpose(X_train)
print("Hasil transpose:")
print(X_train_transpose[0])
print(X_train_transpose[1])
print()

# Convert features datasets into number
lb = LabelBinarizer()
jk_binary = lb.fit_transform(X_train_transpose[1])
print("hasil dari dataset X_train setelah di ubah ke binary")
print(jk_binary)
print()
jk_binary = jk_binary.flatten()
print("setelah di flatten")
print(jk_binary)


dataset X_train:
[[158 'pria']
 [170 'pria']
 [183 'pria']
 [191 'pria']
 [155 'wanita']
 [163 'wanita']
 [180 'wanita']
 [158 'wanita']
 [178 'wanita']]

Hasil transpose:
[158 170 183 191 155 163 180 158 178]
['pria' 'pria' 'pria' 'pria' 'wanita' 'wanita' 'wanita' 'wanita' 'wanita']

hasil dari dataset X_train setelah di ubah ke binary
[[0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]]

setelah di flatten
[0 0 0 0 1 1 1 1 1]


In [86]:
# masukan dataset yang udah diubah ke dataset transpose
X_train_transpose[1] = jk_binary

# hasil dataset yang sudah di ubah ke number
print(X_train_transpose)

[[158 170 183 191 155 163 180 158 178]
 [0 0 0 0 1 1 1 1 1]]


In [90]:
# Hasil daaset yang sudah diubah ke binary
print(X_train.shape)
print(X_train)

(9, 2)
[[158 0]
 [170 0]
 [183 0]
 [191 0]
 [155 1]
 [163 1]
 [180 1]
 [158 1]
 [178 1]]


# Training KNN Regression Model

In [93]:
from sklearn.neighbors import KNeighborsRegressor

K = 3
model = KNeighborsRegressor(n_neighbors=K)
model.fit(X_train, y_train)

KNeighborsRegressor(n_neighbors=3)

# Prediksi Berat Badan

In [113]:
X_new = np.array([[170,0]])
print(X_new.shape)

(1, 2)


In [117]:
y_pred = model.predict(X_new)
print("Tinggi: %d \nPria: %d" % (X_new[0][0], X_new[0][1]))
print("berat badan: %.2f kg." % y_pred)

Tinggi: 170 
Pria: 0
berat badan: 70.67 kg.


In [118]:
# nama = "Rifa Sopyan Syauri"
nama = 33
umur = 21

print("Nama: %d \nUmur: %d \n" % (nama, umur))

Nama: 33 
Umur: 21 



# Evaluasi KNN Regression Model

In [127]:
X_test = np.array([[168,0], [180,0], [160,1], [169,1]])
y_test = np.array([65, 96, 52, 67])

print("X_test:")
print(X_test.shape)
print(X_test)
print()
print("y_test:")
print(y_test.shape)
print(y_test)
print()

print("Prediksi Berat Badan:")
y_pred = model.predict(X_test)
print("y_prediksi:")
print(y_pred)

X_test:
(4, 2)
[[168   0]
 [180   0]
 [160   1]
 [169   1]]

y_test:
(4,)
[65 96 52 67]

Prediksi Berat Badan:
y_prediksi:
[[69.66666667]
 [72.66666667]
 [59.        ]
 [70.66666667]]


### Coeficient of Determination atau R-squared

In [132]:
from sklearn.metrics import r2_score

r_squared = r2_score(y_test, y_pred)

'''
    kalau hasil dari R-Squared nya mendekati angka 1 berarti 
    keakuratan model bagus
''' 
print("R-Squared: %f" % r_squared)

R-Squared: 0.392005


### Mean Absolute Error (MAE) atau Mean Absolute Deviation (MAD)

In [134]:
from sklearn.metrics import mean_absolute_error

MAE = mean_absolute_error(y_test, y_pred)

'''
    kalau hasil dari MAE nya mendekati angka 0 berarti
    keakuratan model bagus
'''

print("MAE: %f" % MAE)

MAE: 9.666667


### Mean Squared Erro (MSE) atau Mean Squared Deviation (MSD)

In [136]:
from sklearn.metrics import mean_squared_error

'''
    Semakin kecil Nilai MSE berarti semakin baik model yang dibuat
'''

MSE = mean_squared_error(y_test, y_pred)
print("MSE: %f" % MSE)

MSE: 157.166667
